name: Build

on:
  push:
    tags:
      - "*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-java@v1
      with:
        java-version: 9

    - uses: actions/setup-python@v1
      with:
        python-version: 2.7

    - name: Build
      run: |
        unset _JAVA_OPTIONS
        bash build.sh
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
            eufix-magisk-*.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
